services:
  - type: web
    name: wine-quality-predictor
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
